---
# Update all packages
# Install tools
# Install and start qemu guest agent
# Reboot if needed
- name: Update all packages
  apt:
    update_cache: yes
    upgrade: dist
- name: Install tools
  apt:
    pkg:
    - net-tools
    - curl
    - unzip
    - nano
    - tcpdump
    - qemu-guest-agent
    - inetutils-ping
- name: Start and enable qemu guest agent
  systemd:
    name: qemu-guest-agent
    state: restarted
    enabled: yes
- name: Check if reboot required
  stat:
    path: /var/run/reboot-required
  register: reboot_required_file
- name: Reboot server after updates
  reboot:
  when: reboot_required_file.stat.exists == true

